controller_list:
  - name: fake_IRB6600_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_Gripper_controller
    joints:
      []