// Generated by gencpp from file robots_start/Battery_positions.msg
// DO NOT EDIT!


#ifndef ROBOTS_START_MESSAGE_BATTERY_POSITIONS_H
#define ROBOTS_START_MESSAGE_BATTERY_POSITIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace robots_start
{
template <class ContainerAllocator>
struct Battery_positions_
{
  typedef Battery_positions_<ContainerAllocator> Type;

  Battery_positions_()
    : box_pose()
    , box_cable_pose()  {
    }
  Battery_positions_(const ContainerAllocator& _alloc)
    : box_pose(_alloc)
    , box_cable_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _box_pose_type;
  _box_pose_type box_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _box_cable_pose_type;
  _box_cable_pose_type box_cable_pose;





  typedef boost::shared_ptr< ::robots_start::Battery_positions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots_start::Battery_positions_<ContainerAllocator> const> ConstPtr;

}; // struct Battery_positions_

typedef ::robots_start::Battery_positions_<std::allocator<void> > Battery_positions;

typedef boost::shared_ptr< ::robots_start::Battery_positions > Battery_positionsPtr;
typedef boost::shared_ptr< ::robots_start::Battery_positions const> Battery_positionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots_start::Battery_positions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots_start::Battery_positions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robots_start::Battery_positions_<ContainerAllocator1> & lhs, const ::robots_start::Battery_positions_<ContainerAllocator2> & rhs)
{
  return lhs.box_pose == rhs.box_pose &&
    lhs.box_cable_pose == rhs.box_cable_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robots_start::Battery_positions_<ContainerAllocator1> & lhs, const ::robots_start::Battery_positions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robots_start

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robots_start::Battery_positions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_start::Battery_positions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_start::Battery_positions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_start::Battery_positions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_start::Battery_positions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_start::Battery_positions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots_start::Battery_positions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c50479c2f12d636a06a12bbea964ddf7";
  }

  static const char* value(const ::robots_start::Battery_positions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc50479c2f12d636aULL;
  static const uint64_t static_value2 = 0x06a12bbea964ddf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robots_start::Battery_positions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots_start/Battery_positions";
  }

  static const char* value(const ::robots_start::Battery_positions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots_start::Battery_positions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose box_pose\n"
"geometry_msgs/Pose box_cable_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robots_start::Battery_positions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots_start::Battery_positions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.box_pose);
      stream.next(m.box_cable_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Battery_positions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots_start::Battery_positions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots_start::Battery_positions_<ContainerAllocator>& v)
  {
    s << indent << "box_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.box_pose);
    s << indent << "box_cable_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.box_cable_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_START_MESSAGE_BATTERY_POSITIONS_H
