// Generated by gencpp from file robots_start/MoverServiceRequest.msg
// DO NOT EDIT!


#ifndef ROBOTS_START_MESSAGE_MOVERSERVICEREQUEST_H
#define ROBOTS_START_MESSAGE_MOVERSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robots_start/MoveitJoints.h>
#include <robots_start/MoveitJoints.h>
#include <robots_start/MoveitJoints.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace robots_start
{
template <class ContainerAllocator>
struct MoverServiceRequest_
{
  typedef MoverServiceRequest_<ContainerAllocator> Type;

  MoverServiceRequest_()
    : joints_input_01()
    , joints_input_02()
    , joints_input_03()
    , target01()
    , target02()
    , target03()
    , target04()
    , target05()
    , target06()
    , target07()
    , target08()
    , target09()
    , target10()
    , target11()
    , target12()
    , target13()
    , target14()
    , target15()
    , target16()
    , target17()
    , target18()
    , target19()
    , target20()
    , target21()
    , target22()
    , target23()
    , target24()
    , target25()
    , target26()
    , target27()
    , target28()
    , target41()
    , target42()
    , target43()
    , target44()
    , target45()
    , target46()
    , target47()
    , target48()
    , target49()
    , target50()
    , target51()
    , target52()
    , target53()
    , target54()
    , target55()
    , target56()
    , target57()
    , target58()
    , target59()
    , target60()
    , target61()
    , target62()
    , target63()
    , target64()
    , target65()
    , target66()
    , target67()
    , target68()
    , target69()
    , target70()
    , target71()
    , target72()
    , target73()
    , target74()
    , target75()
    , target76()
    , target77()
    , target78()
    , target79()
    , target80()
    , target81()
    , target82()
    , target83()
    , target84()
    , target85()
    , target86()
    , target87()
    , target88()
    , target89()
    , target90()
    , target91()
    , target92()
    , target93()
    , target94()
    , target95()
    , target96()
    , target97()
    , target98()
    , target99()
    , target100()
    , target101()
    , target102()
    , target103()
    , target104()
    , target105()
    , target106()
    , target107()
    , target108()
    , target109()
    , target110()
    , target111()
    , target112()
    , target113()
    , target114()
    , target115()
    , target116()
    , target117()
    , target118()
    , target119()
    , target120()
    , target121()
    , target122()
    , target123()
    , target124()
    , target125()
    , target126()
    , target127()
    , target128()
    , target129()
    , target130()
    , target131()
    , target132()
    , target133()
    , target134()
    , target135()
    , target136()  {
    }
  MoverServiceRequest_(const ContainerAllocator& _alloc)
    : joints_input_01(_alloc)
    , joints_input_02(_alloc)
    , joints_input_03(_alloc)
    , target01(_alloc)
    , target02(_alloc)
    , target03(_alloc)
    , target04(_alloc)
    , target05(_alloc)
    , target06(_alloc)
    , target07(_alloc)
    , target08(_alloc)
    , target09(_alloc)
    , target10(_alloc)
    , target11(_alloc)
    , target12(_alloc)
    , target13(_alloc)
    , target14(_alloc)
    , target15(_alloc)
    , target16(_alloc)
    , target17(_alloc)
    , target18(_alloc)
    , target19(_alloc)
    , target20(_alloc)
    , target21(_alloc)
    , target22(_alloc)
    , target23(_alloc)
    , target24(_alloc)
    , target25(_alloc)
    , target26(_alloc)
    , target27(_alloc)
    , target28(_alloc)
    , target41(_alloc)
    , target42(_alloc)
    , target43(_alloc)
    , target44(_alloc)
    , target45(_alloc)
    , target46(_alloc)
    , target47(_alloc)
    , target48(_alloc)
    , target49(_alloc)
    , target50(_alloc)
    , target51(_alloc)
    , target52(_alloc)
    , target53(_alloc)
    , target54(_alloc)
    , target55(_alloc)
    , target56(_alloc)
    , target57(_alloc)
    , target58(_alloc)
    , target59(_alloc)
    , target60(_alloc)
    , target61(_alloc)
    , target62(_alloc)
    , target63(_alloc)
    , target64(_alloc)
    , target65(_alloc)
    , target66(_alloc)
    , target67(_alloc)
    , target68(_alloc)
    , target69(_alloc)
    , target70(_alloc)
    , target71(_alloc)
    , target72(_alloc)
    , target73(_alloc)
    , target74(_alloc)
    , target75(_alloc)
    , target76(_alloc)
    , target77(_alloc)
    , target78(_alloc)
    , target79(_alloc)
    , target80(_alloc)
    , target81(_alloc)
    , target82(_alloc)
    , target83(_alloc)
    , target84(_alloc)
    , target85(_alloc)
    , target86(_alloc)
    , target87(_alloc)
    , target88(_alloc)
    , target89(_alloc)
    , target90(_alloc)
    , target91(_alloc)
    , target92(_alloc)
    , target93(_alloc)
    , target94(_alloc)
    , target95(_alloc)
    , target96(_alloc)
    , target97(_alloc)
    , target98(_alloc)
    , target99(_alloc)
    , target100(_alloc)
    , target101(_alloc)
    , target102(_alloc)
    , target103(_alloc)
    , target104(_alloc)
    , target105(_alloc)
    , target106(_alloc)
    , target107(_alloc)
    , target108(_alloc)
    , target109(_alloc)
    , target110(_alloc)
    , target111(_alloc)
    , target112(_alloc)
    , target113(_alloc)
    , target114(_alloc)
    , target115(_alloc)
    , target116(_alloc)
    , target117(_alloc)
    , target118(_alloc)
    , target119(_alloc)
    , target120(_alloc)
    , target121(_alloc)
    , target122(_alloc)
    , target123(_alloc)
    , target124(_alloc)
    , target125(_alloc)
    , target126(_alloc)
    , target127(_alloc)
    , target128(_alloc)
    , target129(_alloc)
    , target130(_alloc)
    , target131(_alloc)
    , target132(_alloc)
    , target133(_alloc)
    , target134(_alloc)
    , target135(_alloc)
    , target136(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robots_start::MoveitJoints_<ContainerAllocator>  _joints_input_01_type;
  _joints_input_01_type joints_input_01;

   typedef  ::robots_start::MoveitJoints_<ContainerAllocator>  _joints_input_02_type;
  _joints_input_02_type joints_input_02;

   typedef  ::robots_start::MoveitJoints_<ContainerAllocator>  _joints_input_03_type;
  _joints_input_03_type joints_input_03;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target01_type;
  _target01_type target01;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target02_type;
  _target02_type target02;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target03_type;
  _target03_type target03;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target04_type;
  _target04_type target04;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target05_type;
  _target05_type target05;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target06_type;
  _target06_type target06;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target07_type;
  _target07_type target07;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target08_type;
  _target08_type target08;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target09_type;
  _target09_type target09;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target10_type;
  _target10_type target10;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target11_type;
  _target11_type target11;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target12_type;
  _target12_type target12;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target13_type;
  _target13_type target13;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target14_type;
  _target14_type target14;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target15_type;
  _target15_type target15;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target16_type;
  _target16_type target16;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target17_type;
  _target17_type target17;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target18_type;
  _target18_type target18;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target19_type;
  _target19_type target19;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target20_type;
  _target20_type target20;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target21_type;
  _target21_type target21;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target22_type;
  _target22_type target22;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target23_type;
  _target23_type target23;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target24_type;
  _target24_type target24;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target25_type;
  _target25_type target25;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target26_type;
  _target26_type target26;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target27_type;
  _target27_type target27;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target28_type;
  _target28_type target28;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target41_type;
  _target41_type target41;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target42_type;
  _target42_type target42;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target43_type;
  _target43_type target43;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target44_type;
  _target44_type target44;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target45_type;
  _target45_type target45;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target46_type;
  _target46_type target46;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target47_type;
  _target47_type target47;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target48_type;
  _target48_type target48;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target49_type;
  _target49_type target49;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target50_type;
  _target50_type target50;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target51_type;
  _target51_type target51;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target52_type;
  _target52_type target52;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target53_type;
  _target53_type target53;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target54_type;
  _target54_type target54;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target55_type;
  _target55_type target55;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target56_type;
  _target56_type target56;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target57_type;
  _target57_type target57;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target58_type;
  _target58_type target58;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target59_type;
  _target59_type target59;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target60_type;
  _target60_type target60;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target61_type;
  _target61_type target61;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target62_type;
  _target62_type target62;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target63_type;
  _target63_type target63;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target64_type;
  _target64_type target64;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target65_type;
  _target65_type target65;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target66_type;
  _target66_type target66;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target67_type;
  _target67_type target67;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target68_type;
  _target68_type target68;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target69_type;
  _target69_type target69;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target70_type;
  _target70_type target70;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target71_type;
  _target71_type target71;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target72_type;
  _target72_type target72;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target73_type;
  _target73_type target73;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target74_type;
  _target74_type target74;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target75_type;
  _target75_type target75;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target76_type;
  _target76_type target76;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target77_type;
  _target77_type target77;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target78_type;
  _target78_type target78;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target79_type;
  _target79_type target79;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target80_type;
  _target80_type target80;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target81_type;
  _target81_type target81;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target82_type;
  _target82_type target82;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target83_type;
  _target83_type target83;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target84_type;
  _target84_type target84;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target85_type;
  _target85_type target85;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target86_type;
  _target86_type target86;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target87_type;
  _target87_type target87;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target88_type;
  _target88_type target88;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target89_type;
  _target89_type target89;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target90_type;
  _target90_type target90;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target91_type;
  _target91_type target91;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target92_type;
  _target92_type target92;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target93_type;
  _target93_type target93;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target94_type;
  _target94_type target94;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target95_type;
  _target95_type target95;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target96_type;
  _target96_type target96;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target97_type;
  _target97_type target97;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target98_type;
  _target98_type target98;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target99_type;
  _target99_type target99;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target100_type;
  _target100_type target100;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target101_type;
  _target101_type target101;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target102_type;
  _target102_type target102;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target103_type;
  _target103_type target103;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target104_type;
  _target104_type target104;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target105_type;
  _target105_type target105;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target106_type;
  _target106_type target106;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target107_type;
  _target107_type target107;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target108_type;
  _target108_type target108;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target109_type;
  _target109_type target109;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target110_type;
  _target110_type target110;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target111_type;
  _target111_type target111;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target112_type;
  _target112_type target112;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target113_type;
  _target113_type target113;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target114_type;
  _target114_type target114;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target115_type;
  _target115_type target115;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target116_type;
  _target116_type target116;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target117_type;
  _target117_type target117;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target118_type;
  _target118_type target118;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target119_type;
  _target119_type target119;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target120_type;
  _target120_type target120;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target121_type;
  _target121_type target121;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target122_type;
  _target122_type target122;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target123_type;
  _target123_type target123;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target124_type;
  _target124_type target124;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target125_type;
  _target125_type target125;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target126_type;
  _target126_type target126;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target127_type;
  _target127_type target127;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target128_type;
  _target128_type target128;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target129_type;
  _target129_type target129;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target130_type;
  _target130_type target130;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target131_type;
  _target131_type target131;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target132_type;
  _target132_type target132;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target133_type;
  _target133_type target133;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target134_type;
  _target134_type target134;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target135_type;
  _target135_type target135;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target136_type;
  _target136_type target136;





  typedef boost::shared_ptr< ::robots_start::MoverServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots_start::MoverServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoverServiceRequest_

typedef ::robots_start::MoverServiceRequest_<std::allocator<void> > MoverServiceRequest;

typedef boost::shared_ptr< ::robots_start::MoverServiceRequest > MoverServiceRequestPtr;
typedef boost::shared_ptr< ::robots_start::MoverServiceRequest const> MoverServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots_start::MoverServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots_start::MoverServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robots_start::MoverServiceRequest_<ContainerAllocator1> & lhs, const ::robots_start::MoverServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joints_input_01 == rhs.joints_input_01 &&
    lhs.joints_input_02 == rhs.joints_input_02 &&
    lhs.joints_input_03 == rhs.joints_input_03 &&
    lhs.target01 == rhs.target01 &&
    lhs.target02 == rhs.target02 &&
    lhs.target03 == rhs.target03 &&
    lhs.target04 == rhs.target04 &&
    lhs.target05 == rhs.target05 &&
    lhs.target06 == rhs.target06 &&
    lhs.target07 == rhs.target07 &&
    lhs.target08 == rhs.target08 &&
    lhs.target09 == rhs.target09 &&
    lhs.target10 == rhs.target10 &&
    lhs.target11 == rhs.target11 &&
    lhs.target12 == rhs.target12 &&
    lhs.target13 == rhs.target13 &&
    lhs.target14 == rhs.target14 &&
    lhs.target15 == rhs.target15 &&
    lhs.target16 == rhs.target16 &&
    lhs.target17 == rhs.target17 &&
    lhs.target18 == rhs.target18 &&
    lhs.target19 == rhs.target19 &&
    lhs.target20 == rhs.target20 &&
    lhs.target21 == rhs.target21 &&
    lhs.target22 == rhs.target22 &&
    lhs.target23 == rhs.target23 &&
    lhs.target24 == rhs.target24 &&
    lhs.target25 == rhs.target25 &&
    lhs.target26 == rhs.target26 &&
    lhs.target27 == rhs.target27 &&
    lhs.target28 == rhs.target28 &&
    lhs.target41 == rhs.target41 &&
    lhs.target42 == rhs.target42 &&
    lhs.target43 == rhs.target43 &&
    lhs.target44 == rhs.target44 &&
    lhs.target45 == rhs.target45 &&
    lhs.target46 == rhs.target46 &&
    lhs.target47 == rhs.target47 &&
    lhs.target48 == rhs.target48 &&
    lhs.target49 == rhs.target49 &&
    lhs.target50 == rhs.target50 &&
    lhs.target51 == rhs.target51 &&
    lhs.target52 == rhs.target52 &&
    lhs.target53 == rhs.target53 &&
    lhs.target54 == rhs.target54 &&
    lhs.target55 == rhs.target55 &&
    lhs.target56 == rhs.target56 &&
    lhs.target57 == rhs.target57 &&
    lhs.target58 == rhs.target58 &&
    lhs.target59 == rhs.target59 &&
    lhs.target60 == rhs.target60 &&
    lhs.target61 == rhs.target61 &&
    lhs.target62 == rhs.target62 &&
    lhs.target63 == rhs.target63 &&
    lhs.target64 == rhs.target64 &&
    lhs.target65 == rhs.target65 &&
    lhs.target66 == rhs.target66 &&
    lhs.target67 == rhs.target67 &&
    lhs.target68 == rhs.target68 &&
    lhs.target69 == rhs.target69 &&
    lhs.target70 == rhs.target70 &&
    lhs.target71 == rhs.target71 &&
    lhs.target72 == rhs.target72 &&
    lhs.target73 == rhs.target73 &&
    lhs.target74 == rhs.target74 &&
    lhs.target75 == rhs.target75 &&
    lhs.target76 == rhs.target76 &&
    lhs.target77 == rhs.target77 &&
    lhs.target78 == rhs.target78 &&
    lhs.target79 == rhs.target79 &&
    lhs.target80 == rhs.target80 &&
    lhs.target81 == rhs.target81 &&
    lhs.target82 == rhs.target82 &&
    lhs.target83 == rhs.target83 &&
    lhs.target84 == rhs.target84 &&
    lhs.target85 == rhs.target85 &&
    lhs.target86 == rhs.target86 &&
    lhs.target87 == rhs.target87 &&
    lhs.target88 == rhs.target88 &&
    lhs.target89 == rhs.target89 &&
    lhs.target90 == rhs.target90 &&
    lhs.target91 == rhs.target91 &&
    lhs.target92 == rhs.target92 &&
    lhs.target93 == rhs.target93 &&
    lhs.target94 == rhs.target94 &&
    lhs.target95 == rhs.target95 &&
    lhs.target96 == rhs.target96 &&
    lhs.target97 == rhs.target97 &&
    lhs.target98 == rhs.target98 &&
    lhs.target99 == rhs.target99 &&
    lhs.target100 == rhs.target100 &&
    lhs.target101 == rhs.target101 &&
    lhs.target102 == rhs.target102 &&
    lhs.target103 == rhs.target103 &&
    lhs.target104 == rhs.target104 &&
    lhs.target105 == rhs.target105 &&
    lhs.target106 == rhs.target106 &&
    lhs.target107 == rhs.target107 &&
    lhs.target108 == rhs.target108 &&
    lhs.target109 == rhs.target109 &&
    lhs.target110 == rhs.target110 &&
    lhs.target111 == rhs.target111 &&
    lhs.target112 == rhs.target112 &&
    lhs.target113 == rhs.target113 &&
    lhs.target114 == rhs.target114 &&
    lhs.target115 == rhs.target115 &&
    lhs.target116 == rhs.target116 &&
    lhs.target117 == rhs.target117 &&
    lhs.target118 == rhs.target118 &&
    lhs.target119 == rhs.target119 &&
    lhs.target120 == rhs.target120 &&
    lhs.target121 == rhs.target121 &&
    lhs.target122 == rhs.target122 &&
    lhs.target123 == rhs.target123 &&
    lhs.target124 == rhs.target124 &&
    lhs.target125 == rhs.target125 &&
    lhs.target126 == rhs.target126 &&
    lhs.target127 == rhs.target127 &&
    lhs.target128 == rhs.target128 &&
    lhs.target129 == rhs.target129 &&
    lhs.target130 == rhs.target130 &&
    lhs.target131 == rhs.target131 &&
    lhs.target132 == rhs.target132 &&
    lhs.target133 == rhs.target133 &&
    lhs.target134 == rhs.target134 &&
    lhs.target135 == rhs.target135 &&
    lhs.target136 == rhs.target136;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robots_start::MoverServiceRequest_<ContainerAllocator1> & lhs, const ::robots_start::MoverServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robots_start

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_start::MoverServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_start::MoverServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_start::MoverServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "032e266c4810de6bd25d4e203eb2249f";
  }

  static const char* value(const ::robots_start::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x032e266c4810de6bULL;
  static const uint64_t static_value2 = 0xd25d4e203eb2249fULL;
};

template<class ContainerAllocator>
struct DataType< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots_start/MoverServiceRequest";
  }

  static const char* value(const ::robots_start::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MoveitJoints joints_input_01\n"
"MoveitJoints joints_input_02\n"
"MoveitJoints joints_input_03\n"
"\n"
"geometry_msgs/Pose target01\n"
"geometry_msgs/Pose target02\n"
"geometry_msgs/Pose target03\n"
"geometry_msgs/Pose target04\n"
"geometry_msgs/Pose target05\n"
"geometry_msgs/Pose target06\n"
"geometry_msgs/Pose target07\n"
"geometry_msgs/Pose target08\n"
"geometry_msgs/Pose target09\n"
"geometry_msgs/Pose target10\n"
"geometry_msgs/Pose target11\n"
"geometry_msgs/Pose target12\n"
"geometry_msgs/Pose target13\n"
"geometry_msgs/Pose target14\n"
"geometry_msgs/Pose target15\n"
"geometry_msgs/Pose target16\n"
"geometry_msgs/Pose target17\n"
"geometry_msgs/Pose target18\n"
"geometry_msgs/Pose target19\n"
"geometry_msgs/Pose target20\n"
"geometry_msgs/Pose target21\n"
"geometry_msgs/Pose target22\n"
"geometry_msgs/Pose target23\n"
"geometry_msgs/Pose target24\n"
"geometry_msgs/Pose target25\n"
"geometry_msgs/Pose target26\n"
"geometry_msgs/Pose target27\n"
"geometry_msgs/Pose target28\n"
"geometry_msgs/Pose target41\n"
"geometry_msgs/Pose target42\n"
"geometry_msgs/Pose target43\n"
"geometry_msgs/Pose target44\n"
"geometry_msgs/Pose target45\n"
"geometry_msgs/Pose target46\n"
"geometry_msgs/Pose target47\n"
"geometry_msgs/Pose target48\n"
"geometry_msgs/Pose target49\n"
"geometry_msgs/Pose target50\n"
"geometry_msgs/Pose target51\n"
"geometry_msgs/Pose target52\n"
"geometry_msgs/Pose target53\n"
"geometry_msgs/Pose target54\n"
"geometry_msgs/Pose target55\n"
"geometry_msgs/Pose target56\n"
"geometry_msgs/Pose target57\n"
"geometry_msgs/Pose target58\n"
"geometry_msgs/Pose target59\n"
"geometry_msgs/Pose target60\n"
"geometry_msgs/Pose target61\n"
"geometry_msgs/Pose target62\n"
"geometry_msgs/Pose target63\n"
"geometry_msgs/Pose target64\n"
"geometry_msgs/Pose target65\n"
"geometry_msgs/Pose target66\n"
"geometry_msgs/Pose target67\n"
"geometry_msgs/Pose target68\n"
"geometry_msgs/Pose target69\n"
"geometry_msgs/Pose target70\n"
"geometry_msgs/Pose target71\n"
"geometry_msgs/Pose target72\n"
"geometry_msgs/Pose target73\n"
"geometry_msgs/Pose target74\n"
"geometry_msgs/Pose target75\n"
"geometry_msgs/Pose target76\n"
"geometry_msgs/Pose target77\n"
"geometry_msgs/Pose target78\n"
"geometry_msgs/Pose target79\n"
"geometry_msgs/Pose target80\n"
"geometry_msgs/Pose target81\n"
"geometry_msgs/Pose target82\n"
"geometry_msgs/Pose target83\n"
"geometry_msgs/Pose target84\n"
"geometry_msgs/Pose target85\n"
"geometry_msgs/Pose target86\n"
"geometry_msgs/Pose target87\n"
"geometry_msgs/Pose target88\n"
"geometry_msgs/Pose target89\n"
"geometry_msgs/Pose target90\n"
"geometry_msgs/Pose target91\n"
"geometry_msgs/Pose target92\n"
"geometry_msgs/Pose target93\n"
"geometry_msgs/Pose target94\n"
"geometry_msgs/Pose target95\n"
"geometry_msgs/Pose target96\n"
"geometry_msgs/Pose target97\n"
"geometry_msgs/Pose target98\n"
"geometry_msgs/Pose target99\n"
"geometry_msgs/Pose target100\n"
"geometry_msgs/Pose target101\n"
"geometry_msgs/Pose target102\n"
"geometry_msgs/Pose target103\n"
"geometry_msgs/Pose target104\n"
"geometry_msgs/Pose target105\n"
"geometry_msgs/Pose target106\n"
"geometry_msgs/Pose target107\n"
"geometry_msgs/Pose target108\n"
"geometry_msgs/Pose target109\n"
"geometry_msgs/Pose target110\n"
"geometry_msgs/Pose target111\n"
"geometry_msgs/Pose target112\n"
"geometry_msgs/Pose target113\n"
"geometry_msgs/Pose target114\n"
"geometry_msgs/Pose target115\n"
"geometry_msgs/Pose target116\n"
"geometry_msgs/Pose target117\n"
"geometry_msgs/Pose target118\n"
"geometry_msgs/Pose target119\n"
"geometry_msgs/Pose target120\n"
"geometry_msgs/Pose target121\n"
"geometry_msgs/Pose target122\n"
"geometry_msgs/Pose target123\n"
"geometry_msgs/Pose target124\n"
"geometry_msgs/Pose target125\n"
"geometry_msgs/Pose target126\n"
"geometry_msgs/Pose target127\n"
"geometry_msgs/Pose target128\n"
"geometry_msgs/Pose target129\n"
"geometry_msgs/Pose target130\n"
"geometry_msgs/Pose target131\n"
"geometry_msgs/Pose target132\n"
"geometry_msgs/Pose target133\n"
"geometry_msgs/Pose target134\n"
"geometry_msgs/Pose target135\n"
"geometry_msgs/Pose target136\n"
"\n"
"================================================================================\n"
"MSG: robots_start/MoveitJoints\n"
"float64[6] joints_input_01\n"
"float64[6] joints_input_02\n"
"float64[6] joints_input_03\n"
"geometry_msgs/Pose bms\n"
"geometry_msgs/Pose place_pose\n"
"geometry_msgs/Pose batterylock1\n"
"geometry_msgs/Pose batterylock2\n"
"geometry_msgs/Pose batterylock3\n"
"geometry_msgs/Pose batterylock4\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robots_start::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_input_01);
      stream.next(m.joints_input_02);
      stream.next(m.joints_input_03);
      stream.next(m.target01);
      stream.next(m.target02);
      stream.next(m.target03);
      stream.next(m.target04);
      stream.next(m.target05);
      stream.next(m.target06);
      stream.next(m.target07);
      stream.next(m.target08);
      stream.next(m.target09);
      stream.next(m.target10);
      stream.next(m.target11);
      stream.next(m.target12);
      stream.next(m.target13);
      stream.next(m.target14);
      stream.next(m.target15);
      stream.next(m.target16);
      stream.next(m.target17);
      stream.next(m.target18);
      stream.next(m.target19);
      stream.next(m.target20);
      stream.next(m.target21);
      stream.next(m.target22);
      stream.next(m.target23);
      stream.next(m.target24);
      stream.next(m.target25);
      stream.next(m.target26);
      stream.next(m.target27);
      stream.next(m.target28);
      stream.next(m.target41);
      stream.next(m.target42);
      stream.next(m.target43);
      stream.next(m.target44);
      stream.next(m.target45);
      stream.next(m.target46);
      stream.next(m.target47);
      stream.next(m.target48);
      stream.next(m.target49);
      stream.next(m.target50);
      stream.next(m.target51);
      stream.next(m.target52);
      stream.next(m.target53);
      stream.next(m.target54);
      stream.next(m.target55);
      stream.next(m.target56);
      stream.next(m.target57);
      stream.next(m.target58);
      stream.next(m.target59);
      stream.next(m.target60);
      stream.next(m.target61);
      stream.next(m.target62);
      stream.next(m.target63);
      stream.next(m.target64);
      stream.next(m.target65);
      stream.next(m.target66);
      stream.next(m.target67);
      stream.next(m.target68);
      stream.next(m.target69);
      stream.next(m.target70);
      stream.next(m.target71);
      stream.next(m.target72);
      stream.next(m.target73);
      stream.next(m.target74);
      stream.next(m.target75);
      stream.next(m.target76);
      stream.next(m.target77);
      stream.next(m.target78);
      stream.next(m.target79);
      stream.next(m.target80);
      stream.next(m.target81);
      stream.next(m.target82);
      stream.next(m.target83);
      stream.next(m.target84);
      stream.next(m.target85);
      stream.next(m.target86);
      stream.next(m.target87);
      stream.next(m.target88);
      stream.next(m.target89);
      stream.next(m.target90);
      stream.next(m.target91);
      stream.next(m.target92);
      stream.next(m.target93);
      stream.next(m.target94);
      stream.next(m.target95);
      stream.next(m.target96);
      stream.next(m.target97);
      stream.next(m.target98);
      stream.next(m.target99);
      stream.next(m.target100);
      stream.next(m.target101);
      stream.next(m.target102);
      stream.next(m.target103);
      stream.next(m.target104);
      stream.next(m.target105);
      stream.next(m.target106);
      stream.next(m.target107);
      stream.next(m.target108);
      stream.next(m.target109);
      stream.next(m.target110);
      stream.next(m.target111);
      stream.next(m.target112);
      stream.next(m.target113);
      stream.next(m.target114);
      stream.next(m.target115);
      stream.next(m.target116);
      stream.next(m.target117);
      stream.next(m.target118);
      stream.next(m.target119);
      stream.next(m.target120);
      stream.next(m.target121);
      stream.next(m.target122);
      stream.next(m.target123);
      stream.next(m.target124);
      stream.next(m.target125);
      stream.next(m.target126);
      stream.next(m.target127);
      stream.next(m.target128);
      stream.next(m.target129);
      stream.next(m.target130);
      stream.next(m.target131);
      stream.next(m.target132);
      stream.next(m.target133);
      stream.next(m.target134);
      stream.next(m.target135);
      stream.next(m.target136);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoverServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots_start::MoverServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots_start::MoverServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "joints_input_01: ";
    s << std::endl;
    Printer< ::robots_start::MoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input_01);
    s << indent << "joints_input_02: ";
    s << std::endl;
    Printer< ::robots_start::MoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input_02);
    s << indent << "joints_input_03: ";
    s << std::endl;
    Printer< ::robots_start::MoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input_03);
    s << indent << "target01: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target01);
    s << indent << "target02: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target02);
    s << indent << "target03: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target03);
    s << indent << "target04: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target04);
    s << indent << "target05: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target05);
    s << indent << "target06: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target06);
    s << indent << "target07: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target07);
    s << indent << "target08: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target08);
    s << indent << "target09: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target09);
    s << indent << "target10: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target10);
    s << indent << "target11: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target11);
    s << indent << "target12: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target12);
    s << indent << "target13: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target13);
    s << indent << "target14: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target14);
    s << indent << "target15: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target15);
    s << indent << "target16: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target16);
    s << indent << "target17: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target17);
    s << indent << "target18: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target18);
    s << indent << "target19: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target19);
    s << indent << "target20: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target20);
    s << indent << "target21: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target21);
    s << indent << "target22: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target22);
    s << indent << "target23: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target23);
    s << indent << "target24: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target24);
    s << indent << "target25: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target25);
    s << indent << "target26: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target26);
    s << indent << "target27: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target27);
    s << indent << "target28: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target28);
    s << indent << "target41: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target41);
    s << indent << "target42: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target42);
    s << indent << "target43: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target43);
    s << indent << "target44: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target44);
    s << indent << "target45: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target45);
    s << indent << "target46: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target46);
    s << indent << "target47: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target47);
    s << indent << "target48: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target48);
    s << indent << "target49: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target49);
    s << indent << "target50: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target50);
    s << indent << "target51: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target51);
    s << indent << "target52: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target52);
    s << indent << "target53: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target53);
    s << indent << "target54: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target54);
    s << indent << "target55: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target55);
    s << indent << "target56: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target56);
    s << indent << "target57: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target57);
    s << indent << "target58: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target58);
    s << indent << "target59: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target59);
    s << indent << "target60: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target60);
    s << indent << "target61: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target61);
    s << indent << "target62: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target62);
    s << indent << "target63: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target63);
    s << indent << "target64: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target64);
    s << indent << "target65: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target65);
    s << indent << "target66: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target66);
    s << indent << "target67: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target67);
    s << indent << "target68: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target68);
    s << indent << "target69: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target69);
    s << indent << "target70: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target70);
    s << indent << "target71: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target71);
    s << indent << "target72: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target72);
    s << indent << "target73: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target73);
    s << indent << "target74: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target74);
    s << indent << "target75: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target75);
    s << indent << "target76: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target76);
    s << indent << "target77: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target77);
    s << indent << "target78: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target78);
    s << indent << "target79: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target79);
    s << indent << "target80: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target80);
    s << indent << "target81: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target81);
    s << indent << "target82: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target82);
    s << indent << "target83: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target83);
    s << indent << "target84: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target84);
    s << indent << "target85: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target85);
    s << indent << "target86: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target86);
    s << indent << "target87: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target87);
    s << indent << "target88: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target88);
    s << indent << "target89: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target89);
    s << indent << "target90: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target90);
    s << indent << "target91: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target91);
    s << indent << "target92: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target92);
    s << indent << "target93: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target93);
    s << indent << "target94: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target94);
    s << indent << "target95: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target95);
    s << indent << "target96: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target96);
    s << indent << "target97: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target97);
    s << indent << "target98: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target98);
    s << indent << "target99: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target99);
    s << indent << "target100: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target100);
    s << indent << "target101: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target101);
    s << indent << "target102: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target102);
    s << indent << "target103: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target103);
    s << indent << "target104: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target104);
    s << indent << "target105: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target105);
    s << indent << "target106: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target106);
    s << indent << "target107: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target107);
    s << indent << "target108: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target108);
    s << indent << "target109: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target109);
    s << indent << "target110: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target110);
    s << indent << "target111: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target111);
    s << indent << "target112: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target112);
    s << indent << "target113: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target113);
    s << indent << "target114: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target114);
    s << indent << "target115: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target115);
    s << indent << "target116: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target116);
    s << indent << "target117: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target117);
    s << indent << "target118: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target118);
    s << indent << "target119: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target119);
    s << indent << "target120: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target120);
    s << indent << "target121: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target121);
    s << indent << "target122: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target122);
    s << indent << "target123: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target123);
    s << indent << "target124: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target124);
    s << indent << "target125: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target125);
    s << indent << "target126: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target126);
    s << indent << "target127: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target127);
    s << indent << "target128: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target128);
    s << indent << "target129: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target129);
    s << indent << "target130: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target130);
    s << indent << "target131: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target131);
    s << indent << "target132: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target132);
    s << indent << "target133: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target133);
    s << indent << "target134: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target134);
    s << indent << "target135: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target135);
    s << indent << "target136: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target136);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_START_MESSAGE_MOVERSERVICEREQUEST_H
