// Generated by gencpp from file robots_start/MoverService2.msg
// DO NOT EDIT!


#ifndef ROBOTS_START_MESSAGE_MOVERSERVICE2_H
#define ROBOTS_START_MESSAGE_MOVERSERVICE2_H

#include <ros/service_traits.h>


#include <robots_start/MoverService2Request.h>
#include <robots_start/MoverService2Response.h>


namespace robots_start
{

struct MoverService2
{

typedef MoverService2Request Request;
typedef MoverService2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoverService2
} // namespace robots_start


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robots_start::MoverService2 > {
  static const char* value()
  {
    return "a6b0f7c9c76a11297038273db05e9cbd";
  }

  static const char* value(const ::robots_start::MoverService2&) { return value(); }
};

template<>
struct DataType< ::robots_start::MoverService2 > {
  static const char* value()
  {
    return "robots_start/MoverService2";
  }

  static const char* value(const ::robots_start::MoverService2&) { return value(); }
};


// service_traits::MD5Sum< ::robots_start::MoverService2Request> should match
// service_traits::MD5Sum< ::robots_start::MoverService2 >
template<>
struct MD5Sum< ::robots_start::MoverService2Request>
{
  static const char* value()
  {
    return MD5Sum< ::robots_start::MoverService2 >::value();
  }
  static const char* value(const ::robots_start::MoverService2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_start::MoverService2Request> should match
// service_traits::DataType< ::robots_start::MoverService2 >
template<>
struct DataType< ::robots_start::MoverService2Request>
{
  static const char* value()
  {
    return DataType< ::robots_start::MoverService2 >::value();
  }
  static const char* value(const ::robots_start::MoverService2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robots_start::MoverService2Response> should match
// service_traits::MD5Sum< ::robots_start::MoverService2 >
template<>
struct MD5Sum< ::robots_start::MoverService2Response>
{
  static const char* value()
  {
    return MD5Sum< ::robots_start::MoverService2 >::value();
  }
  static const char* value(const ::robots_start::MoverService2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_start::MoverService2Response> should match
// service_traits::DataType< ::robots_start::MoverService2 >
template<>
struct DataType< ::robots_start::MoverService2Response>
{
  static const char* value()
  {
    return DataType< ::robots_start::MoverService2 >::value();
  }
  static const char* value(const ::robots_start::MoverService2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTS_START_MESSAGE_MOVERSERVICE2_H
