// Generated by gencpp from file robots_start/MoverService.msg
// DO NOT EDIT!


#ifndef ROBOTS_START_MESSAGE_MOVERSERVICE_H
#define ROBOTS_START_MESSAGE_MOVERSERVICE_H

#include <ros/service_traits.h>


#include <robots_start/MoverServiceRequest.h>
#include <robots_start/MoverServiceResponse.h>


namespace robots_start
{

struct MoverService
{

typedef MoverServiceRequest Request;
typedef MoverServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoverService
} // namespace robots_start


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robots_start::MoverService > {
  static const char* value()
  {
    return "c44af60b9394ecf6f3d5ea1f70a99bb3";
  }

  static const char* value(const ::robots_start::MoverService&) { return value(); }
};

template<>
struct DataType< ::robots_start::MoverService > {
  static const char* value()
  {
    return "robots_start/MoverService";
  }

  static const char* value(const ::robots_start::MoverService&) { return value(); }
};


// service_traits::MD5Sum< ::robots_start::MoverServiceRequest> should match
// service_traits::MD5Sum< ::robots_start::MoverService >
template<>
struct MD5Sum< ::robots_start::MoverServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robots_start::MoverService >::value();
  }
  static const char* value(const ::robots_start::MoverServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_start::MoverServiceRequest> should match
// service_traits::DataType< ::robots_start::MoverService >
template<>
struct DataType< ::robots_start::MoverServiceRequest>
{
  static const char* value()
  {
    return DataType< ::robots_start::MoverService >::value();
  }
  static const char* value(const ::robots_start::MoverServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robots_start::MoverServiceResponse> should match
// service_traits::MD5Sum< ::robots_start::MoverService >
template<>
struct MD5Sum< ::robots_start::MoverServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robots_start::MoverService >::value();
  }
  static const char* value(const ::robots_start::MoverServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robots_start::MoverServiceResponse> should match
// service_traits::DataType< ::robots_start::MoverService >
template<>
struct DataType< ::robots_start::MoverServiceResponse>
{
  static const char* value()
  {
    return DataType< ::robots_start::MoverService >::value();
  }
  static const char* value(const ::robots_start::MoverServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTS_START_MESSAGE_MOVERSERVICE_H
