// Generated by gencpp from file robots_start/MoverService03Request.msg
// DO NOT EDIT!


#ifndef ROBOTS_START_MESSAGE_MOVERSERVICE03REQUEST_H
#define ROBOTS_START_MESSAGE_MOVERSERVICE03REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robots_start/MoveitJoints.h>
#include <robots_start/MoveitJoints.h>
#include <robots_start/MoveitJoints.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace robots_start
{
template <class ContainerAllocator>
struct MoverService03Request_
{
  typedef MoverService03Request_<ContainerAllocator> Type;

  MoverService03Request_()
    : joints_input_01()
    , joints_input_02()
    , joints_input_03()
    , target01()
    , target02()
    , target03()
    , target04()
    , target05()
    , target06()
    , target07()
    , target08()
    , target09()
    , target10()
    , target11()
    , target12()  {
    }
  MoverService03Request_(const ContainerAllocator& _alloc)
    : joints_input_01(_alloc)
    , joints_input_02(_alloc)
    , joints_input_03(_alloc)
    , target01(_alloc)
    , target02(_alloc)
    , target03(_alloc)
    , target04(_alloc)
    , target05(_alloc)
    , target06(_alloc)
    , target07(_alloc)
    , target08(_alloc)
    , target09(_alloc)
    , target10(_alloc)
    , target11(_alloc)
    , target12(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robots_start::MoveitJoints_<ContainerAllocator>  _joints_input_01_type;
  _joints_input_01_type joints_input_01;

   typedef  ::robots_start::MoveitJoints_<ContainerAllocator>  _joints_input_02_type;
  _joints_input_02_type joints_input_02;

   typedef  ::robots_start::MoveitJoints_<ContainerAllocator>  _joints_input_03_type;
  _joints_input_03_type joints_input_03;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target01_type;
  _target01_type target01;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target02_type;
  _target02_type target02;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target03_type;
  _target03_type target03;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target04_type;
  _target04_type target04;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target05_type;
  _target05_type target05;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target06_type;
  _target06_type target06;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target07_type;
  _target07_type target07;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target08_type;
  _target08_type target08;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target09_type;
  _target09_type target09;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target10_type;
  _target10_type target10;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target11_type;
  _target11_type target11;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target12_type;
  _target12_type target12;





  typedef boost::shared_ptr< ::robots_start::MoverService03Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots_start::MoverService03Request_<ContainerAllocator> const> ConstPtr;

}; // struct MoverService03Request_

typedef ::robots_start::MoverService03Request_<std::allocator<void> > MoverService03Request;

typedef boost::shared_ptr< ::robots_start::MoverService03Request > MoverService03RequestPtr;
typedef boost::shared_ptr< ::robots_start::MoverService03Request const> MoverService03RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots_start::MoverService03Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots_start::MoverService03Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robots_start::MoverService03Request_<ContainerAllocator1> & lhs, const ::robots_start::MoverService03Request_<ContainerAllocator2> & rhs)
{
  return lhs.joints_input_01 == rhs.joints_input_01 &&
    lhs.joints_input_02 == rhs.joints_input_02 &&
    lhs.joints_input_03 == rhs.joints_input_03 &&
    lhs.target01 == rhs.target01 &&
    lhs.target02 == rhs.target02 &&
    lhs.target03 == rhs.target03 &&
    lhs.target04 == rhs.target04 &&
    lhs.target05 == rhs.target05 &&
    lhs.target06 == rhs.target06 &&
    lhs.target07 == rhs.target07 &&
    lhs.target08 == rhs.target08 &&
    lhs.target09 == rhs.target09 &&
    lhs.target10 == rhs.target10 &&
    lhs.target11 == rhs.target11 &&
    lhs.target12 == rhs.target12;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robots_start::MoverService03Request_<ContainerAllocator1> & lhs, const ::robots_start::MoverService03Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robots_start

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robots_start::MoverService03Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots_start::MoverService03Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_start::MoverService03Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots_start::MoverService03Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_start::MoverService03Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots_start::MoverService03Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots_start::MoverService03Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a4469f0eccc2a01b51cd14ff0b309b1";
  }

  static const char* value(const ::robots_start::MoverService03Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a4469f0eccc2a01ULL;
  static const uint64_t static_value2 = 0xb51cd14ff0b309b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robots_start::MoverService03Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots_start/MoverService03Request";
  }

  static const char* value(const ::robots_start::MoverService03Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots_start::MoverService03Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MoveitJoints joints_input_01\n"
"MoveitJoints joints_input_02\n"
"MoveitJoints joints_input_03\n"
"\n"
"geometry_msgs/Pose target01\n"
"geometry_msgs/Pose target02\n"
"geometry_msgs/Pose target03\n"
"geometry_msgs/Pose target04\n"
"geometry_msgs/Pose target05\n"
"geometry_msgs/Pose target06\n"
"geometry_msgs/Pose target07\n"
"geometry_msgs/Pose target08\n"
"geometry_msgs/Pose target09\n"
"geometry_msgs/Pose target10\n"
"geometry_msgs/Pose target11\n"
"geometry_msgs/Pose target12\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robots_start/MoveitJoints\n"
"float64[6] joints_input_01\n"
"float64[6] joints_input_02\n"
"float64[6] joints_input_03\n"
"geometry_msgs/Pose bms\n"
"geometry_msgs/Pose place_pose\n"
"geometry_msgs/Pose batterylock1\n"
"geometry_msgs/Pose batterylock2\n"
"geometry_msgs/Pose batterylock3\n"
"geometry_msgs/Pose batterylock4\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robots_start::MoverService03Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots_start::MoverService03Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_input_01);
      stream.next(m.joints_input_02);
      stream.next(m.joints_input_03);
      stream.next(m.target01);
      stream.next(m.target02);
      stream.next(m.target03);
      stream.next(m.target04);
      stream.next(m.target05);
      stream.next(m.target06);
      stream.next(m.target07);
      stream.next(m.target08);
      stream.next(m.target09);
      stream.next(m.target10);
      stream.next(m.target11);
      stream.next(m.target12);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoverService03Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots_start::MoverService03Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots_start::MoverService03Request_<ContainerAllocator>& v)
  {
    s << indent << "joints_input_01: ";
    s << std::endl;
    Printer< ::robots_start::MoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input_01);
    s << indent << "joints_input_02: ";
    s << std::endl;
    Printer< ::robots_start::MoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input_02);
    s << indent << "joints_input_03: ";
    s << std::endl;
    Printer< ::robots_start::MoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input_03);
    s << indent << "target01: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target01);
    s << indent << "target02: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target02);
    s << indent << "target03: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target03);
    s << indent << "target04: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target04);
    s << indent << "target05: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target05);
    s << indent << "target06: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target06);
    s << indent << "target07: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target07);
    s << indent << "target08: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target08);
    s << indent << "target09: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target09);
    s << indent << "target10: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target10);
    s << indent << "target11: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target11);
    s << indent << "target12: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target12);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_START_MESSAGE_MOVERSERVICE03REQUEST_H
