MoveitJoints joints_input_01
MoveitJoints joints_input_02
MoveitJoints joints_input_03

geometry_msgs/Pose target01
geometry_msgs/Pose target02
geometry_msgs/Pose target03
geometry_msgs/Pose target04
geometry_msgs/Pose target05
geometry_msgs/Pose target06
geometry_msgs/Pose target07
geometry_msgs/Pose target08
geometry_msgs/Pose target09
geometry_msgs/Pose target10
geometry_msgs/Pose target11
geometry_msgs/Pose target12
geometry_msgs/Pose target13
geometry_msgs/Pose target14
geometry_msgs/Pose target15
geometry_msgs/Pose target16
geometry_msgs/Pose target17
geometry_msgs/Pose target18
geometry_msgs/Pose target19
geometry_msgs/Pose target20
geometry_msgs/Pose target21
geometry_msgs/Pose target22
geometry_msgs/Pose target23
geometry_msgs/Pose target24
geometry_msgs/Pose target25
geometry_msgs/Pose target26
geometry_msgs/Pose target27
geometry_msgs/Pose target28
geometry_msgs/Pose target41
geometry_msgs/Pose target42
geometry_msgs/Pose target43
geometry_msgs/Pose target44
geometry_msgs/Pose target45
geometry_msgs/Pose target46
geometry_msgs/Pose target47
geometry_msgs/Pose target48
geometry_msgs/Pose target49
geometry_msgs/Pose target50
geometry_msgs/Pose target51
geometry_msgs/Pose target52
geometry_msgs/Pose target53
geometry_msgs/Pose target54
geometry_msgs/Pose target55
geometry_msgs/Pose target56
geometry_msgs/Pose target57
geometry_msgs/Pose target58
geometry_msgs/Pose target59
geometry_msgs/Pose target60
geometry_msgs/Pose target61
geometry_msgs/Pose target62
geometry_msgs/Pose target63
geometry_msgs/Pose target64
geometry_msgs/Pose target65
geometry_msgs/Pose target66
geometry_msgs/Pose target67
geometry_msgs/Pose target68
geometry_msgs/Pose target69
geometry_msgs/Pose target70
geometry_msgs/Pose target71
geometry_msgs/Pose target72
geometry_msgs/Pose target73
geometry_msgs/Pose target74
geometry_msgs/Pose target75
geometry_msgs/Pose target76
geometry_msgs/Pose target77
geometry_msgs/Pose target78
geometry_msgs/Pose target79
geometry_msgs/Pose target80
geometry_msgs/Pose target81
geometry_msgs/Pose target82
geometry_msgs/Pose target83
geometry_msgs/Pose target84
geometry_msgs/Pose target85
geometry_msgs/Pose target86
geometry_msgs/Pose target87
geometry_msgs/Pose target88
geometry_msgs/Pose target89
geometry_msgs/Pose target90
geometry_msgs/Pose target91
geometry_msgs/Pose target92
geometry_msgs/Pose target93
geometry_msgs/Pose target94
geometry_msgs/Pose target95
geometry_msgs/Pose target96
geometry_msgs/Pose target97
geometry_msgs/Pose target98
geometry_msgs/Pose target99
geometry_msgs/Pose target100
geometry_msgs/Pose target101
geometry_msgs/Pose target102
geometry_msgs/Pose target103
geometry_msgs/Pose target104
geometry_msgs/Pose target105
geometry_msgs/Pose target106
geometry_msgs/Pose target107
geometry_msgs/Pose target108
geometry_msgs/Pose target109
geometry_msgs/Pose target110
geometry_msgs/Pose target111
geometry_msgs/Pose target112
geometry_msgs/Pose target113
geometry_msgs/Pose target114
geometry_msgs/Pose target115
geometry_msgs/Pose target116
geometry_msgs/Pose target117
geometry_msgs/Pose target118
geometry_msgs/Pose target119
geometry_msgs/Pose target120
geometry_msgs/Pose target121
geometry_msgs/Pose target122
geometry_msgs/Pose target123
geometry_msgs/Pose target124
geometry_msgs/Pose target125
geometry_msgs/Pose target126
geometry_msgs/Pose target127
geometry_msgs/Pose target128
geometry_msgs/Pose target129
geometry_msgs/Pose target130
geometry_msgs/Pose target131
geometry_msgs/Pose target132
geometry_msgs/Pose target133
geometry_msgs/Pose target134
geometry_msgs/Pose target135
geometry_msgs/Pose target136
---
moveit_msgs/RobotTrajectory[] trajectory01
moveit_msgs/RobotTrajectory[] trajectory02
moveit_msgs/RobotTrajectory[] trajectory03
moveit_msgs/RobotTrajectory[] trajectory04
moveit_msgs/RobotTrajectory[] trajectory05
moveit_msgs/RobotTrajectory[] trajectory06
moveit_msgs/RobotTrajectory[] trajectory07
moveit_msgs/RobotTrajectory[] trajectory11
moveit_msgs/RobotTrajectory[] trajectory12
moveit_msgs/RobotTrajectory[] trajectory13
moveit_msgs/RobotTrajectory[] trajectory14
moveit_msgs/RobotTrajectory[] trajectory15
moveit_msgs/RobotTrajectory[] trajectory16
moveit_msgs/RobotTrajectory[] trajectory17
moveit_msgs/RobotTrajectory[] trajectory18
moveit_msgs/RobotTrajectory[] trajectory19
moveit_msgs/RobotTrajectory[] trajectory20
moveit_msgs/RobotTrajectory[] trajectory21
moveit_msgs/RobotTrajectory[] trajectory22
moveit_msgs/RobotTrajectory[] trajectory23
moveit_msgs/RobotTrajectory[] trajectory24
moveit_msgs/RobotTrajectory[] trajectory25
moveit_msgs/RobotTrajectory[] trajectory26
moveit_msgs/RobotTrajectory[] trajectory27
moveit_msgs/RobotTrajectory[] trajectory28
moveit_msgs/RobotTrajectory[] trajectory29
moveit_msgs/RobotTrajectory[] trajectory30
moveit_msgs/RobotTrajectory[] trajectory31
moveit_msgs/RobotTrajectory[] trajectory32
moveit_msgs/RobotTrajectory[] trajectory33
moveit_msgs/RobotTrajectory[] trajectory34


