(cl:defpackage robots_start-srv
  (:use )
  (:export
   "MOVERSERVICE"
   "<MOVERSERVICE-REQUEST>"
   "MOVERSERVICE-REQUEST"
   "<MOVERSERVICE-RESPONSE>"
   "MOVERSERVICE-RESPONSE"
   "MOVERSERVICE03"
   "<MOVERSERVICE03-REQUEST>"
   "MOVERSERVICE03-REQUEST"
   "<MOVERSERVICE03-RESPONSE>"
   "MOVERSERVICE03-RESPONSE"
   "MOVERSERVICE1"
   "<MOVERSERVICE1-REQUEST>"
   "MOVERSERVICE1-REQUEST"
   "<MOVERSERVICE1-RESPONSE>"
   "MOVERSERVICE1-RESPONSE"
  ))

