(cl:in-package robots_start-srv)
(cl:export '(JOINTS_INPUT_01-VAL
          JOINTS_INPUT_01
          JOINTS_INPUT_02-VAL
          JOINTS_INPUT_02
          JOINTS_INPUT_03-VAL
          JOINTS_INPUT_03
          TARGET01-VAL
          TARGET01
          TARGET02-VAL
          TARGET02
          TARGET03-VAL
          TARGET03
          TARGET04-VAL
          TARGET04
          TARGET05-VAL
          TARGET05
          TARGET06-VAL
          TARGET06
          TARGET07-VAL
          TARGET07
          TARGET08-VAL
          TARGET08
          TARGET09-VAL
          TARGET09
          TARGET10-VAL
          TARGET10
          TARGET11-VAL
          TARGET11
          TARGET12-VAL
          TARGET12
          TRAJECTORIES_01-VAL
          TRAJECTORIES_01
          TRAJECTORIES_02-VAL
          TRAJECTORIES_02
          TRAJECTORIES_03-VAL
          TRAJECTORIES_03
))