(cl:in-package robots_start-srv)
(cl:export '(JOINTS_INPUT_IRB03-VAL
          JOINTS_INPUT_IRB03
          JOINTS_INPUT_UR5_05-VAL
          JOINTS_INPUT_UR5_05
          JOINTS_INPUT_UR5_06-VAL
          JOINTS_INPUT_UR5_06
          TARGET01-VAL
          TARGET01
          TARGET02-VAL
          TARGET02
          TARGET03-VAL
          TARGET03
          TARGET04-VAL
          TARGET04
          TARGET05-VAL
          TARGET05
          TARGET06-VAL
          TARGET06
          TARGET07-VAL
          TARGET07
          TARGET08-VAL
          TARGET08
          TARGET09-VAL
          TARGET09
          TARGET10-VAL
          TARGET10
          TARGET11-VAL
          TARGET11
          TARGET12-VAL
          TARGET12
          TARGET13-VAL
          TARGET13
          TARGET14-VAL
          TARGET14
          TARGET15-VAL
          TARGET15
          TARGET16-VAL
          TARGET16
          TARGET17-VAL
          TARGET17
          TARGET18-VAL
          TARGET18
          TARGET19-VAL
          TARGET19
          TARGET20-VAL
          TARGET20
          TARGET21-VAL
          TARGET21
          TARGET22-VAL
          TARGET22
          TARGET23-VAL
          TARGET23
          TARGET24-VAL
          TARGET24
          TARGET25-VAL
          TARGET25
          TARGET26-VAL
          TARGET26
          TARGET27-VAL
          TARGET27
          TARGET28-VAL
          TARGET28
          TARGET29-VAL
          TARGET29
          TARGET30-VAL
          TARGET30
          TARGET31-VAL
          TARGET31
          TARGET32-VAL
          TARGET32
          TARGET33-VAL
          TARGET33
          TARGET34-VAL
          TARGET34
          TARGET35-VAL
          TARGET35
          TARGET36-VAL
          TARGET36
          TARGET37-VAL
          TARGET37
          TARGET38-VAL
          TARGET38
          TARGET39-VAL
          TARGET39
          TARGET40-VAL
          TARGET40
          TARGET41-VAL
          TARGET41
          TARGET42-VAL
          TARGET42
          TARGET43-VAL
          TARGET43
          TARGET44-VAL
          TARGET44
          TARGET45-VAL
          TARGET45
          TARGET46-VAL
          TARGET46
          TARGET47-VAL
          TARGET47
          TARGET48-VAL
          TARGET48
          TARGET49-VAL
          TARGET49
          TARGET50-VAL
          TARGET50
          TARGET51-VAL
          TARGET51
          TARGET52-VAL
          TARGET52
          TARGET53-VAL
          TARGET53
          TARGET54-VAL
          TARGET54
          TARGET55-VAL
          TARGET55
          TARGET56-VAL
          TARGET56
          TARGET57-VAL
          TARGET57
          TARGET58-VAL
          TARGET58
          TARGET59-VAL
          TARGET59
          TARGET60-VAL
          TARGET60
          TARGET61-VAL
          TARGET61
          TARGET62-VAL
          TARGET62
          TARGET63-VAL
          TARGET63
          TARGET64-VAL
          TARGET64
          TARGET65-VAL
          TARGET65
          TARGET66-VAL
          TARGET66
          TARGET67-VAL
          TARGET67
          TARGET68-VAL
          TARGET68
          TARGET69-VAL
          TARGET69
          TARGET70-VAL
          TARGET70
          TARGET71-VAL
          TARGET71
          TARGET72-VAL
          TARGET72
          TARGET73-VAL
          TARGET73
          TARGET74-VAL
          TARGET74
          TARGET75-VAL
          TARGET75
          TARGET76-VAL
          TARGET76
          TARGET77-VAL
          TARGET77
          TARGET78-VAL
          TARGET78
          TARGET79-VAL
          TARGET79
          TARGET80-VAL
          TARGET80
          TARGET81-VAL
          TARGET81
          TARGET82-VAL
          TARGET82
          TARGET83-VAL
          TARGET83
          TARGET84-VAL
          TARGET84
          TARGET85-VAL
          TARGET85
          TARGET86-VAL
          TARGET86
          TARGET87-VAL
          TARGET87
          TARGET88-VAL
          TARGET88
          TARGET89-VAL
          TARGET89
          TARGET90-VAL
          TARGET90
          TARGET91-VAL
          TARGET91
          TARGET92-VAL
          TARGET92
          TARGET93-VAL
          TARGET93
          TARGET94-VAL
          TARGET94
          TARGET95-VAL
          TARGET95
          TARGET96-VAL
          TARGET96
          TARGET97-VAL
          TARGET97
          TARGET98-VAL
          TARGET98
          TARGET99-VAL
          TARGET99
          TARGET100-VAL
          TARGET100
          TRAJECTORIES_01-VAL
          TRAJECTORIES_01
          TRAJECTORIES_02-VAL
          TRAJECTORIES_02
          TRAJECTORIES_03-VAL
          TRAJECTORIES_03
          TRAJECTORIES_04-VAL
          TRAJECTORIES_04
          TRAJECTORIES_05-VAL
          TRAJECTORIES_05
          TRAJECTORIES_06-VAL
          TRAJECTORIES_06
          TRAJECTORIES_07-VAL
          TRAJECTORIES_07
          TRAJECTORIES_08-VAL
          TRAJECTORIES_08
          TRAJECTORIES_09-VAL
          TRAJECTORIES_09
          TRAJECTORIES_10-VAL
          TRAJECTORIES_10
          TRAJECTORIES_11-VAL
          TRAJECTORIES_11
          TRAJECTORIES_12-VAL
          TRAJECTORIES_12
          TRAJECTORIES_13-VAL
          TRAJECTORIES_13
          TRAJECTORIES_14-VAL
          TRAJECTORIES_14
          TRAJECTORIES_15-VAL
          TRAJECTORIES_15
          TRAJECTORIES_16-VAL
          TRAJECTORIES_16
          TRAJECTORIES_17-VAL
          TRAJECTORIES_17
          TRAJECTORIES_18-VAL
          TRAJECTORIES_18
          TRAJECTORIES_19-VAL
          TRAJECTORIES_19
          TRAJECTORIES_20-VAL
          TRAJECTORIES_20
          TRAJECTORIES_21-VAL
          TRAJECTORIES_21
          TRAJECTORIES_22-VAL
          TRAJECTORIES_22
          TRAJECTORIES_23-VAL
          TRAJECTORIES_23
          TRAJECTORIES_24-VAL
          TRAJECTORIES_24
          TRAJECTORIES_25-VAL
          TRAJECTORIES_25
))